env:
  es2017: true
  browser: true
  commonjs: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'

rules:
  no-tabs: off
  indent:
      - error
      - tab
  react/jsx-indent:
      - error
      - tab
  semi: off
