env:
  es2017: true
  browser: true
  commonjs: true
  jest: true


extends: [ "plugin:react/recommended", "plugin:@typescript-eslint/recommended"]
globals:
  process: true

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'

rules:
  react/prop-types: 0
  semi: off
